game: sokoban
dataset: dataset/sokoban/1
output: vlm_eval_results/sokoban

models:
  - name: gpt-5
    type: api
    base_url: https://newapi.deepwisdom.ai/v1
    max_tokens: 60000
    temperature: 1.0
  - name: gemini-2.5-pro
    type: api
    base_url: https://newapi.deepwisdom.ai/v1
    max_tokens: 60000
    temperature: 1.0
  - name: Qwen/Qwen2.5-VL-7B-Instruct
    type: api
    base_url: http://localhost:8123/v1
    max_tokens: 10000
    temperature: 1.0

workers: 10
max_levels: -1
assets_folder: skins/sokoban/1

